//
//  Constants.h
//  OverlayView
//
//  Created by user on 08/05/15.
//  Copyright (c) 2015 user. All rights reserved.
//

#ifndef OverlayView_Constants_h
#define OverlayView_Constants_h

#define radians(x) ((x) / 180.0 * M_PI)
#define degrees(x) (180 * x / M_PI)


#define INITAL_CAMERA_HEIGHT 130
#define MOTION_UPDATE_INTERVAL 0.5
#define HEIGHT_UPDATE_INTERVAL 0.25
#define DISTANCE_UPDATE_INTERVAL 0.25
#define GUIDE_UPDATE_INTERVAL1 6
#define GUIDE_UPDATE_INTERVAL2 3
#define GUIDE_CLEAR_INTERVAL 6
#define ANIMATION_DURATION 2
#define CROSS_HAIR_WIDTH 130
#define CROSS_HAIR_HEIGHT 130
#define MAXIMUM_SLIDER_VALUE 300
#define MINIMUM_SLIDER_VALUE 10
#define CURRENT_SLIDER_VALUE 130
#define SLIDER_VALUE_WIDTH 85
#define SLIDER_VALUE_HEIGHT 30
#define SLIDER_IMAGE_WIDTH 7
#define SLIDER_HEIGHT_OFFSET 140
#define SLIDER_ORIGIN_OFFSET_Y_1 45
#define SLIDER_ORIGIN_OFFSET_Y_2 15
#define SLIDER_WIDTH 30
#define SLIDER_CLEARANCE_1 100
#define SLIDER_CLEARANCE_2 90
#define SLIDER_VALUE_POSTION_CORRECTION_OFFSET -20
#define SLIDER_VALUE_POSTION_CORRECTION_FACTOR 30
#define BUTTON_WIDTH 110
#define BUTTON_HEIGHT 50
#define BUTTON_CORNER_RADIUS 20
#define HEIGHT_OUTPUT_FONT_SIZE 19
#define BACKGROUND_COLOR_RED 0.23137254902
#define BACKGROUND_COLOR_GREEN 0.34901960784
#define BACKGROUND_COLOR_BLUE 0.59607843137
#define GUIDE_BACKGROUND_COLOR_RED 0.46274509803
#define GUIDE_BACKGROUND_COLOR_GREEN 0.46274509803
#define GUIDE_BACKGROUND_COLOR_BLUE 0.46274509803
#define GUIDE_BACKGROUND_ALPHA 0.5
#define FULL_OPAQUE_ALPHA 1
#define TRANSPARENT_ALPHA 0.4
#define YAW_CHANGE_CUTOFF_ANGLE 35
#define GUIDE_LABEL_HEIGHT 40
#define HEIGHT_MEASURING_MODE 1
#define DISTANCE_MEASURING_MODE 2
#define DIMENSION_MEASURING_MODE 3
#define HEIGHT_SLIDER_GUIDE 1
#define CALIBRATE_GUIDE 2
#define CAPTURE_GUIDE 3
#define MARK_POSITION1_GUIDE 4
#define DISTANCE_GUIDE 5
#define MARK_BASE_GUIDE 6
#define CALCULATE_HEIGHT_GUIDE 7
#define NEGATIVE_YAW -1
#define POSITIVE_YAW 1
#define GUIDE_IMAGE_SIZE 400
#define GUIDE_IMAGE_SIZE_SMALL 300
#define POINTER_GUIDE_X_OFFSET -10
#define POINTER_GUIDE_Y_OFFSET -10
#define POINTER_GUIDE_Y_OFFSET_SMALL 40
#define POINTER_GUIDE_Y_OFFSET_SMALL_1 30
#define CALIBERATE_GUIDE_X_OFFSET 40
#define CALIBERATE_GUIDE_Y_OFFSET 110
#define MAXIMUM_DEVICE_HEIGHT_FOR_TOP_GUIDE 700
#define GUIDE_HIDE_INTERVAL 8
#define HOME_BUTTON_X_POSITION -40
#define MENU_BUTTON_GAP 5
#define MENU_BUTTON_OFFSET 0
#define BUTTON_POSITION_FACTOR 2.5
#define INFO_BUTTON_POSITION_FACTOR 0.5


#define CAMERA_TRANSFORM_X 1
#define CAMERA_TRANSFORM_Y 1.24299
#define BUTTON1TAG 1
#define BUTTON2TAG 2
#define MEASUREMENT_FACTORS @[@"1.00",@"0.01",@"0.0328084",@"0.393701"]
#define MEASUREMENT_UNITS  @[@"Centimeter", @"Meter", @"Foot", @"Inch"]
#define MEASUREMENT_UNITS_SHORT_FORM  @[@"cm", @"m", @"ft", @"inch"]
#define BUTTON_CORNER_RADIUS 20
#define BUTTON_DRAG_OFFSET_X -15
#define BUTTON_DRAG_OFFSET_Y 30
#define LINE_OFFSET_X -16
#define LINE_OFFSET_Y 52
#define INITIAL_LINE_X 19
#define INITIAL_LINE_Y 52
#define FUNCTION_CALL_INTERVAL 0.25
#define DISTANCE_OUTPUT_WIDTH 120
#define DISTANCE_OUTPUT_HEIGHT 30
#define OUTPUT_LABEL_LINE_VERTICAL_OFFSET 20
#define OUTPUT_LABEL_LINE_HORIZONTAL_OFFSET 85
#define TRANSPARENT_ALPHA 0.4
#define TOP_BAR_HEIGHT 42
#define MARKER_BUTTON_HEIGHT 52
#define MARKER_BUTTON_WIDTH 41




#endif


